name: qg_shifts_webhook
version: "3.9"

services:
  qg_shifts_webhook:
    container_name: qg_shifts_webhook
    build:
      context: .
      dockerfile: Dockerfile
    image: qg_shifts_webhook:latest
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/app/logs
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  default:
    name: qg_shifts_webhook-net
